#!/bin/bash

clear

files=`ls src/*.c`

echo "Creating build directory..."

mkdir -p build/src

echo "Compiling src tree..."

for file in $files
do
	echo "Compiling: $file"

	gcc -c -g -Wno-discarded-qualifiers $file -o build/$file.o
done

echo "Linking executable..."

gcc -g build/src/* -o build/horizon